// Writes src/pdf/pictures.js: the outline pictures a word page can carry,
// copied out of Tabler Icons (MIT, in node_modules/@tabler/icons). Only the
// words listed here ship, so the browser bundle stays small. Every Tabler
// outline icon is a 24 × 24 grid of <path> elements with a 2-unit round
// stroke; the paths are kept as they are.
// Usage: node scripts/pictures.mjs (after changing WORDS)
import { readFileSync, writeFileSync } from "node:fs";

// word -> Tabler outline icon name
const WORDS = {
  // Halloween
  bat: "bat", cat: "cat", moon: "moon", mask: "mask", leaf: "leaf", bone: "bone", star: "star", wand: "wand",
  skull: "skull", candy: "candy", ghost: "ghost-2", grave: "grave-2", apple: "apple", acorn: "acorn", spider: "spider",
  candle: "candle", cookie: "cookie", pumpkin: "pumpkin-scary", lollipop: "lollipop", mushroom: "mushroom",
  // Thanksgiving
  mug: "mug", cake: "cake", bowl: "bowl", home: "home", bread: "bread", wheat: "wheat", maple: "leaf-maple",
  glass: "glass", carrot: "carrot", cherry: "cherry", teapot: "teapot", pepper: "pepper", feather: "feather", seedling: "seedling",
  // Christmas
  ball: "ball-basketball", gift: "gift", bell: "bell", sock: "sock", book: "book", train: "train", robot: "robot",
  sleigh: "sleigh", snowman: "snowman", reindeer: "deer", deer: "deer", ornament: "christmas-ball", snowflake: "snowflake",
  gingerbread: "cookie-man", tree: "tree",
  // Everyday words a buyer may type
  dog: "dog", fish: "fish", sun: "sun", car: "car", key: "key", cup: "cup", umbrella: "umbrella", heart: "heart",
  boat: "sailboat", bus: "bus", bike: "bike", plane: "plane", rocket: "rocket", flower: "flower", lemon: "lemon",
  cloud: "cloud", rain: "cloud-rain", butterfly: "butterfly", bug: "bug", paw: "paw", crown: "crown", shirt: "shirt",
  shoe: "shoe", glasses: "eyeglass", clock: "clock", lamp: "lamp", chair: "armchair", bed: "bed", door: "door",
  window: "window", pencil: "pencil", scissors: "cut", pizza: "pizza", milk: "milk", horse: "horse", pig: "pig",
  egg: "egg", balloon: "balloon", piano: "piano", tent: "tent", anchor: "anchor", flag: "flag", cactus: "cactus",
  plant: "plant", tractor: "tractor", truck: "truck", helicopter: "helicopter", scooter: "scooter", rainbow: "rainbow",
  camera: "camera", phone: "phone", backpack: "backpack", school: "school", globe: "globe", map: "map", dice: "dice",
  bucket: "bucket", shovel: "shovel", hammer: "hammer", ladder: "ladder", bottle: "bottle", flame: "flame", fire: "flame",
};

const dir = new URL("../node_modules/@tabler/icons/icons/outline/", import.meta.url);
const pkg = JSON.parse(readFileSync(new URL("../node_modules/@tabler/icons/package.json", import.meta.url), "utf8"));
const out = {};
for (const [word, icon] of Object.entries(WORDS)) {
  const svg = readFileSync(new URL(`${icon}.svg`, dir), "utf8");
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length || /<(circle|rect|line|polyline|ellipse|polygon)\b/.test(svg)) throw new Error(`${icon}: not plain paths`);
  out[word] = paths;
}
const lines = Object.entries(out).map(([w, p]) => `  ${JSON.stringify(w)}: ${JSON.stringify(p)},`);
writeFileSync(new URL("../src/pdf/pictures.js", import.meta.url), `// Generated by scripts/pictures.mjs from Tabler Icons ${pkg.version} — do not edit.
// Outline pictures for word pages: each is SVG paths on a 24 × 24 grid, y down,
// drawn as a round 2-unit stroke.
//
// Tabler Icons, https://tabler.io/icons
// MIT License. Copyright (c) 2020-2026 Paweł Kuna.
// The full licence text is public/licenses/tabler-icons.txt.
export const PICTURES = {
${lines.join("\n")}
};

// The picture for a word page, if there is one: the word itself, any case,
// or the word without a final "s" (bats, apples).
export function pictureFor(word) {
  const w = String(word ?? "").trim().toLowerCase();
  return PICTURES[w] ?? (w.endsWith("s") ? PICTURES[w.slice(0, -1)] : undefined) ?? null;
}
`);
console.log(`wrote src/pdf/pictures.js: ${Object.keys(out).length} words`);
