import { readFileSync, writeFileSync } from "node:fs";
import { renderBook } from "./src/pdf/book.js";
import { renderCover } from "./src/pdf/cover.js";
const fonts = { bold: readFileSync("fonts/LiberationSans-Bold.ttf"), regular: readFileSync("fonts/LiberationSans-Regular.ttf") };
const [out] = process.argv.slice(2);
const t0 = Date.now();
const b = await renderBook({ trim: "8.5x11", guideIn: 0.75 }, fonts);
const b2 = await renderBook({ trim: "6x9", guideIn: 0.45, licensed: true }, fonts);
const c = await renderCover({ title: "T", trim: "6x9" }, fonts);
console.log("ms", Date.now() - t0, "sizes", b.length, b2.length, c.length);
writeFileSync(out + "-a.pdf", b); writeFileSync(out + "-b.pdf", b2); writeFileSync(out + "-c.pdf", c);
