// One clue per built-in word, for the crossword type. Definition-style,
// written to be solvable from general knowledge, never containing the answer.
// Keys are the normalised word (lower case, letters only) so they line up
// with wordlists.js after normalizeWord().
//
// A unit test checks every theme word has a clue and no clue leaks its answer.

export const CLUES = {
  // ---- animals
  alligator: "Toothy reptile of the Florida swamps",
  antelope: "Swift horned grazer of the African plains",
  armadillo: "Mammal in a jointed bony shell",
  baboon: "Large monkey with a dog-like face",
  badger: "Striped-faced burrower with a bad temper",
  bear: "Big furry animal that sleeps through winter",
  beaver: "Dam-building rodent with a flat tail",
  bison: "Shaggy North American plains grazer",
  buffalo: "Water-loving relative of the ox",
  camel: "Desert beast with one hump or two",
  cheetah: "Fastest land animal",
  chimpanzee: "Our closest ape relative",
  cougar: "Mountain lion",
  coyote: "Wild dog known for its howl",
  deer: "Antlered forest grazer",
  dolphin: "Playful, clicking sea mammal",
  donkey: "Long-eared beast of burden",
  elephant: "Largest land animal, with a trunk",
  elk: "Large deer with sweeping antlers",
  ferret: "Slim, curious pet related to the weasel",
  flamingo: "Pink bird that stands on one leg",
  fox: "Red, bushy-tailed cunning one",
  gazelle: "Graceful antelope that bounds",
  giraffe: "Tallest animal, with a spotted neck",
  goat: "Bearded climber that eats almost anything",
  gorilla: "Largest of the great apes",
  hamster: "Pocket-sized pet with cheek pouches",
  hedgehog: "Small nocturnal animal covered in spines",
  hippo: "River-dwelling heavyweight, for short",
  horse: "Animal ridden with a saddle",
  hyena: "Scavenger with a laughing cry",
  iguana: "Large green lizard",
  jaguar: "Spotted big cat of the Americas",
  kangaroo: "Bounding marsupial with a pouch",
  koala: "Sleepy eucalyptus eater",
  lemur: "Big-eyed primate of Madagascar",
  leopard: "Spotted cat that drags prey up trees",
  lion: "King of the jungle",
  llama: "Woolly Andean pack animal",
  lynx: "Tufted-eared wild cat",
  meerkat: "Upright-standing desert lookout",
  mongoose: "Small carnivore that fights snakes",
  monkey: "Tree-swinging primate with a tail",
  moose: "Largest deer, with broad flat antlers",
  mouse: "Tiny rodent a cat chases",
  narwhal: "Whale with a single long tusk",
  ocelot: "Small spotted wild cat",
  octopus: "Eight-armed sea creature",
  orangutan: "Red-haired ape of Borneo",
  otter: "Playful swimmer that floats on its back",
  panda: "Black-and-white bamboo eater",
  panther: "Black big cat",
  parrot: "Colourful bird that can mimic speech",
  pelican: "Sea bird with a pouch under its beak",
  penguin: "Flightless bird in a black-and-white suit",
  platypus: "Egg-laying mammal with a duck bill",
  porcupine: "Rodent bristling with quills",
  rabbit: "Long-eared hopper",
  raccoon: "Masked night-time raider of bins",
  reindeer: "Antlered animal that pulls a famous sleigh",
  rhino: "Thick-skinned charger with a nose horn, for short",
  seal: "Whiskered swimmer that barks",
  sheep: "Woolly flock animal",
  skunk: "Black-and-white animal with a foul spray",
  sloth: "Slowest tree-dweller",
  squirrel: "Bushy-tailed nut hoarder",
  tiger: "Striped big cat",
  toucan: "Tropical bird with an enormous beak",
  turtle: "Reptile that carries its home",
  walrus: "Tusked, whiskered Arctic heavyweight",
  weasel: "Slim, sly hunter",
  whale: "Largest animal in the sea",
  wolf: "Pack hunter that howls at the moon",
  wombat: "Stocky Australian burrower",
  yak: "Long-haired ox of the Himalayas",
  zebra: "Striped horse of the savanna",

  // ---- food
  almond: "Nut used for marzipan",
  apple: "Fruit that keeps the doctor away",
  avocado: "Green fruit mashed for guacamole",
  bacon: "Cured pork strips for breakfast",
  bagel: "Ring-shaped bread roll",
  banana: "Yellow fruit sold in bunches",
  basil: "Herb in pesto",
  biscuit: "Small baked treat to dunk in tea",
  blueberry: "Small dark fruit in muffins",
  broccoli: "Green vegetable like a little tree",
  burrito: "Filled and rolled tortilla",
  butter: "Spread churned from cream",
  cabbage: "Leafy head made into coleslaw",
  carrot: "Orange root a rabbit loves",
  cashew: "Kidney-shaped nut",
  celery: "Crunchy green stalks",
  cereal: "Breakfast in a bowl with milk",
  cheese: "Dairy food that may be aged",
  cherry: "Small red fruit with a stone",
  chicken: "Most common poultry",
  chocolate: "Sweet made from cocoa",
  cinnamon: "Spice from a curled bark",
  coconut: "Hairy fruit with milk inside",
  coffee: "Morning drink from roasted beans",
  cookie: "Sweet round biscuit, American style",
  cucumber: "Cool green salad vegetable",
  cupcake: "Single-serving bake in a paper case, iced on top",
  donut: "Fried ring with a hole",
  dumpling: "Dough parcel, often steamed",
  eggplant: "Purple vegetable, aubergine",
  garlic: "Pungent bulb in cloves",
  ginger: "Hot root used in baking",
  grape: "Fruit that becomes wine",
  honey: "Sweet made by bees",
  lasagna: "Layered pasta bake",
  lemon: "Sour yellow citrus",
  lettuce: "Base of most salads",
  mango: "Tropical fruit with a large flat stone",
  muffin: "Cupcake's plainer cousin",
  mushroom: "Fungus that is food",
  noodle: "Long strand in a bowl of broth",
  oatmeal: "Warm breakfast porridge",
  olive: "Small fruit pressed for oil",
  onion: "Layered bulb that makes you cry",
  orange: "Citrus that shares its name with a colour",
  pancake: "Batter round flipped for Shrove Tuesday",
  papaya: "Orange-fleshed tropical fruit with black seeds",
  pasta: "Italian staple of many shapes",
  peach: "Fuzzy stone fruit",
  peanut: "Legume roasted as a snack",
  pepper: "Spice ground beside the salt",
  pickle: "Cucumber preserved in brine",
  pizza: "Topped flatbread baked in a hot oven",
  popcorn: "Cinema snack that pops",
  potato: "Starchy root for chips and mash",
  pretzel: "Knotted salted bread",
  pumpkin: "Big orange squash carved in autumn",
  quinoa: "Protein-rich seed cooked like rice",
  radish: "Small peppery red root",
  raisin: "Dried grape",
  salad: "Bowl of mixed raw vegetables",
  salmon: "Pink-fleshed fish",
  sandwich: "Filling between two slices of bread",
  sausage: "Meat in a casing",
  spinach: "Leafy green a sailor ate for strength",
  strawberry: "Red summer fruit with seeds outside",
  sushi: "Japanese rice dish, often with raw fish",
  taco: "Folded tortilla with a filling",
  tomato: "Red fruit treated as a vegetable",
  turkey: "Bird roasted for Thanksgiving",
  vanilla: "Flavour from an orchid pod",
  waffle: "Grid-patterned breakfast cake",
  walnut: "Wrinkled nut that looks like a brain",
  yogurt: "Cultured milk in a pot",
  zucchini: "Green summer squash, courgette",

  // ---- travel
  airport: "Where flights depart",
  adventure: "Exciting, risky undertaking",
  backpack: "Bag carried on the shoulders",
  beach: "Sandy shore",
  boarding: "Getting on the plane",
  bridge: "Structure that spans a river",
  cabin: "Small wooden house, or the inside of a car",
  camping: "Sleeping in a tent",
  canyon: "Deep gorge cut by a river",
  castle: "Fortified home of a king; also a chess move",
  coast: "Where the land meets the sea",
  compass: "Needle that points north",
  cruise: "Holiday aboard a ship",
  customs: "Border checkpoint for luggage",
  desert: "Dry, sandy region",
  embassy: "A country's office abroad",
  explore: "Travel to discover",
  ferry: "Boat that carries people across water",
  forest: "Large area of trees",
  glacier: "Slow river of ice",
  harbor: "Sheltered place for ships",
  highway: "Major road between cities",
  hostel: "Cheap lodging with shared rooms",
  hotel: "Place with rooms to rent by the night",
  island: "Ground surrounded by water",
  itinerary: "Planned route of a journey",
  journey: "Travel from one place to another",
  jungle: "Dense tropical forest",
  lagoon: "Shallow water cut off by a reef",
  landmark: "Famous, recognisable feature",
  luggage: "Bags you travel with",
  market: "Place of stalls and traders",
  meadow: "Field of grass and wildflowers",
  monument: "Statue or building that commemorates",
  mountain: "Very high peak",
  museum: "Building where treasures are displayed",
  ocean: "Vast body of salt water",
  passport: "Booklet needed to cross borders",
  pilgrim: "Traveller to a holy place",
  plaza: "Public square",
  postcard: "Picture mailed from a holiday, wish you were here",
  railway: "Track for trains",
  resort: "Holiday complex by the sea or snow",
  river: "Flowing fresh water",
  safari: "Trip to see wild animals",
  souvenir: "Keepsake from a trip",
  station: "Where trains stop",
  suitcase: "Hard-sided luggage with a handle",
  summit: "Top of a mountain",
  sunset: "Evening sky show",
  temple: "Place of worship",
  ticket: "Proof you paid for the ride",
  tourist: "Sightseeing visitor",
  trail: "Marked path for walkers",
  train: "Carriages pulled along rails",
  tunnel: "Passage through a hill",
  valley: "Low land between hills",
  village: "Small rural settlement",
  visa: "Stamp permitting entry to a country",
  volcano: "Mountain that erupts",
  voyage: "Long journey by sea",
  waterfall: "River dropping over a cliff",

  // ---- garden
  acorn: "Oak tree's nut",
  azalea: "Showy shrub with spring blooms",
  bamboo: "Fast-growing giant grass",
  bark: "Outer covering of a tree",
  beetle: "Insect with hard wing cases",
  blossom: "Flowers on a fruit tree",
  bluebell: "Woodland flower carpeting spring",
  branch: "Limb of a tree",
  breeze: "Gentle wind",
  bulb: "Underground store a tulip grows from",
  butterfly: "Insect with colourful wings",
  cactus: "Spiny desert plant",
  clover: "Three-leaf plant, lucky with four",
  compost: "Rotted scraps that feed the soil",
  daffodil: "Yellow trumpet of early spring",
  dahlia: "Showy late-summer bloom",
  daisy: "White petals round a yellow centre",
  dandelion: "Weed with a puffball of seeds",
  fern: "Frond-bearing plant of shady spots",
  fertilizer: "Feed for plants",
  foxglove: "Tall spike of thimble-shaped flowers",
  geranium: "Bright window-box favourite",
  greenhouse: "Glass building for tender plants",
  harvest: "Gathering in the crops",
  hedge: "Row of shrubs as a fence",
  hibiscus: "Tropical bloom with a long stamen",
  hollyhock: "Tall cottage-garden spire",
  honeysuckle: "Climber with sweet-scented flowers",
  hyacinth: "Fragrant spring bulb",
  iris: "Flower named for the rainbow goddess",
  ivy: "Evergreen that climbs walls",
  jasmine: "Star-shaped scented flower",
  ladybug: "Red beetle with black spots",
  lavender: "Purple herb with a calming scent",
  lawn: "Mown grass",
  lilac: "Shrub with purple spring clusters",
  lily: "Trumpet-shaped flower, often white",
  magnolia: "Tree with big waxy blooms",
  marigold: "Orange flower that deters pests",
  moss: "Soft green carpet on damp stone",
  mulch: "Bark layer spread over soil",
  nectar: "Sweet liquid bees collect",
  orchid: "Exotic bloom on a slender stem",
  pansy: "Flower with a face",
  peony: "Blowsy pink bloom of early summer",
  petal: "One coloured part of a flower",
  petunia: "Trailing summer bedding flower",
  pollen: "Yellow dust that makes you sneeze",
  poppy: "Red flower of remembrance",
  primrose: "Pale yellow flower of early spring",
  pruning: "Cutting back a shrub",
  rake: "Tool for gathering leaves",
  rose: "Thorny flower of love",
  seedling: "Newly sprouted plant",
  shovel: "Tool for digging",
  snapdragon: "Flower that opens like a mouth when squeezed",
  sprout: "To begin to grow",
  sunflower: "Tall bloom that follows the sun",
  thistle: "Prickly purple flower, emblem of Scotland",
  trellis: "Lattice for climbing plants",
  trowel: "Small hand spade",
  tulip: "Cup-shaped bulb flower of Holland",
  violet: "Small purple woodland flower",
  watering: "Giving plants a drink",
  wheelbarrow: "One-wheeled garden cart",
  wisteria: "Climber dripping with purple clusters",
  zinnia: "Bright daisy-like summer bloom",

  // ---- ocean
  anchor: "Heavy hook that holds a ship in place",
  anemone: "Sea creature that looks like a flower",
  barnacle: "Shellfish that clings to hulls",
  barracuda: "Long, toothy predatory fish",
  clam: "Two-shelled mollusc dug from sand",
  coral: "Reef-building sea creature",
  crab: "Sideways-walking shellfish with claws",
  current: "Steady flow of water",
  driftwood: "Timber washed up by the sea",
  eel: "Snake-like fish",
  flounder: "Flatfish with both eyes on one side",
  grouper: "Big-mouthed reef fish",
  jellyfish: "Stinging see-through drifter",
  kelp: "Giant brown seaweed",
  krill: "Tiny shrimp that whales feed on",
  lighthouse: "Tower that warns ships",
  lobster: "Clawed shellfish served with butter",
  mackerel: "Oily striped fish",
  manatee: "Gentle sea cow",
  marlin: "Fish with a long spear-like bill",
  mussel: "Blue-black shellfish steamed in wine",
  nautilus: "Mollusc in a spiral chambered shell",
  orca: "Killer whale",
  oyster: "Shellfish that may hold a pearl",
  pearl: "Gem grown inside a shell",
  plankton: "Drifting food of the sea",
  porpoise: "Small, blunt-nosed relative of the dolphin",
  puffin: "Sea bird with a striped beak",
  reef: "Ridge of rock or coral near the surface",
  sandbar: "Shallow ridge just under the water, a hazard to boats",
  sardine: "Small fish packed in a tin",
  scallop: "Shellfish with a fan-shaped shell",
  seahorse: "Upright fish with a curled tail",
  seashell: "What you hold to your ear at the beach",
  seaweed: "Marine plant on the rocks",
  shark: "Feared fish with rows of teeth",
  shrimp: "Small curved shellfish for cocktails",
  snorkel: "Tube for breathing face-down in water",
  sponge: "Soft sea animal used in the bath",
  squid: "Ten-armed creature with an ink sac",
  starfish: "Five-armed sea creature",
  stingray: "Flat fish with a barbed tail",
  submarine: "Vessel that travels underwater",
  surf: "Breaking waves",
  swordfish: "Big ocean hunter with a flat, sharp bill",
  tide: "Twice-daily rise and fall of the sea",
  trench: "Deepest part of the ocean floor",
  tuna: "Big fish canned for sandwiches",
  urchin: "Spiny ball on the seabed",
  wave: "Ridge of water rolling to shore",

  // ---- space
  asteroid: "Rocky body orbiting the sun",
  astronaut: "Space traveller",
  atmosphere: "Layer of gas around a planet",
  aurora: "Northern lights",
  blackhole: "Region nothing escapes, not even light",
  capsule: "Small crew compartment of a spacecraft",
  comet: "Icy body with a glowing tail",
  constellation: "Named pattern of stars",
  cosmos: "The universe; also a daisy-like garden flower",
  crater: "Bowl-shaped dent from an impact",
  eclipse: "One heavenly body hiding another",
  galaxy: "Vast island of stars",
  gravity: "Force that keeps your feet on the ground",
  helmet: "Space suit's head covering",
  jupiter: "Largest planet",
  launch: "Send a rocket skyward",
  lunar: "Of the moon",
  mars: "The red planet",
  mercury: "Planet nearest the sun",
  meteor: "Shooting star",
  milkyway: "Our home galaxy",
  moon: "Earth's natural satellite",
  nebula: "Glowing cloud of gas and dust",
  neptune: "Farthest planet, deep blue",
  nova: "Star that suddenly brightens",
  orbit: "Path around a planet or star",
  planet: "Large body circling a star",
  pluto: "Demoted dwarf planet",
  probe: "Unmanned craft sent to explore",
  pulsar: "Spinning star that flashes like a beacon",
  quasar: "Extremely bright distant galaxy core",
  rocket: "Vehicle that blasts off",
  rover: "Wheeled explorer on another world",
  satellite: "Object that orbits a planet",
  saturn: "Ringed planet",
  shuttle: "Reusable winged spacecraft",
  solar: "Of the sun",
  star: "Ball of burning gas in the night sky",
  sun: "Our nearest star",
  telescope: "Instrument for viewing distant objects",
  thruster: "Small engine for steering a craft",
  titan: "Saturn's largest moon",
  universe: "Everything that exists",
  uranus: "Planet that spins on its side",
  venus: "Hottest planet, Earth's neighbour",
  void: "Empty space",
  zenith: "Point directly overhead",

  // ---- christmas
  angel: "Winged figure atop the tree",
  bells: "They jingle on a sleigh",
  blizzard: "Severe snowstorm",
  candle: "Wax stick with a wick",
  candycane: "Striped hooked sweet",
  carol: "Festive song sung door to door",
  chimney: "Santa's way in",
  cocoa: "Hot chocolate drink",
  cookies: "Sweet baked rounds, American style",
  eggnog: "Creamy festive drink",
  elf: "Santa's small helper",
  evergreen: "Tree that keeps its leaves all year",
  family: "Relatives gathered together",
  fireplace: "Where the stockings hang",
  frost: "Icy coating on a winter morning",
  garland: "Decorative chain of greenery",
  gift: "Wrapped present",
  gingerbread: "Spiced biscuit shaped like a person",
  holly: "Prickly leaves and red berries",
  icicle: "Hanging spike of ice",
  jingle: "Sound of small bells",
  joy: "Great happiness",
  lights: "Strings that twinkle on the tree",
  mistletoe: "Kiss beneath it",
  nativity: "Scene of the birth in the stable",
  noel: "Christmas, in a carol",
  nutcracker: "Toy soldier of a famous ballet",
  ornament: "Bauble hung on the tree",
  parade: "Procession down the main street",
  peace: "What the carol wishes on earth",
  pine: "Evergreen with needles",
  poinsettia: "Red-leaved festive plant",
  presents: "What is under the tree on the morning",
  ribbon: "Strip tied in a bow on a gift",
  santa: "Bearded man in red",
  scarf: "Wrapped around the neck in winter",
  sled: "Runner-borne vehicle for snowy hills",
  sleigh: "Reindeer-drawn vehicle",
  snowflake: "Six-sided ice crystal",
  snowman: "Figure built in the garden with a carrot nose",
  stocking: "Hung by the fire to be filled",
  tinsel: "Glittery strands on the tree",
  tradition: "Custom passed down the years",
  tree: "Decorated centrepiece of the season",
  wreath: "Ring of greenery on the door",
  yule: "Old word for the festive season",

  // ---- sports
  archery: "Sport of bows and arrows",
  athlete: "Person who competes in sport",
  badminton: "Racket game with a shuttlecock",
  baseball: "Game of bats, bases and innings",
  basketball: "Game of hoops and dribbling",
  bowling: "Knocking down ten pins",
  boxing: "Sport of gloved punches",
  champion: "The winner of the title",
  coach: "Person who trains the team",
  cricket: "Game of wickets and overs",
  curling: "Sliding stones on ice with brooms",
  cycling: "Sport on two wheels",
  defense: "Keeping the other side from scoring",
  diving: "Plunging headfirst from a board",
  fencing: "Sword sport of thrust and parry",
  football: "Game played with a pigskin, or soccer",
  goal: "What a striker aims for",
  golf: "Game of clubs, holes and greens",
  gymnastics: "Sport of vaults, bars and beams",
  handball: "Court game of throwing into a net",
  hockey: "Stick-and-puck game on ice",
  hurdles: "Race over barriers",
  javelin: "Thrown spear in athletics",
  judo: "Japanese throwing martial art",
  karate: "Martial art of strikes and chops",
  kayak: "Narrow paddled boat",
  lacrosse: "Game with netted sticks",
  marathon: "26.2-mile race",
  medal: "Disc awarded on the podium",
  offense: "The attacking side",
  olympics: "Games held every four years",
  paddle: "Blade used to move a canoe",
  pitcher: "Player who throws to the batter",
  polo: "Horseback game with mallets",
  racket: "Strung bat for tennis",
  referee: "Official with the whistle",
  relay: "Race run in stages with a baton",
  rowing: "Racing in oared boats",
  rugby: "Game of scrums and tries",
  sailing: "Sport of wind-powered boats",
  skating: "Gliding on blades",
  skiing: "Sliding downhill on two planks",
  soccer: "The world's most played game",
  sprint: "Short, fast race",
  stadium: "Arena for big matches",
  surfing: "Riding waves on a board",
  swimming: "Racing in lanes in a pool",
  tennis: "Game of love, deuce and sets",
  trophy: "Cup handed to the winner",
  volleyball: "Game played over a high net",
  wrestling: "Grappling sport",

  // ---- music
  accordion: "Squeezebox with keys",
  acoustic: "Unplugged, of a guitar",
  album: "Collection of recorded songs",
  anthem: "Song of a nation or a team",
  ballad: "Slow, storytelling song",
  banjo: "Twangy round-bodied string instrument",
  baritone: "Male voice between tenor and bass",
  bass: "Deepest voice or guitar; also a freshwater fish",
  beat: "The pulse you tap your foot to",
  cello: "Large string instrument played seated",
  chord: "Several notes sounded together",
  chorus: "The part of a song that repeats",
  clarinet: "Black woodwind with a single reed",
  composer: "Writer of music",
  concert: "Live performance for an audience",
  conductor: "Leader with a baton",
  drums: "Kit struck with sticks",
  duet: "Piece for two performers",
  encore: "Extra song after the applause",
  flute: "Silver woodwind held sideways",
  guitar: "Six-stringed instrument",
  harmony: "Notes that agree with the melody",
  harp: "Tall plucked instrument of many strings",
  jazz: "Improvised music born in New Orleans",
  keyboard: "Piano's electronic cousin",
  lyrics: "The words of a song",
  melody: "The tune",
  microphone: "What a singer holds",
  note: "Single musical sound",
  oboe: "Double-reed woodwind that tunes the orchestra",
  octave: "Interval of eight notes",
  opera: "Drama that is sung throughout",
  orchestra: "Large ensemble of strings, winds and brass",
  percussion: "Instruments you hit",
  piano: "Keyboard instrument of eighty-eight keys",
  pitch: "How high or low a note is",
  quartet: "Group of four players",
  rhythm: "Pattern of beats",
  saxophone: "Brass-bodied reed instrument of jazz",
  scale: "Notes in ascending order, or a kitchen weigher",
  singer: "Vocalist",
  solo: "Performance by one",
  soprano: "Highest female voice",
  symphony: "Large orchestral work in movements",
  tempo: "Speed of the music",
  tenor: "High male voice",
  trombone: "Brass instrument with a slide",
  trumpet: "Bright brass with three valves",
  tuba: "Deepest brass instrument",
  ukulele: "Small four-string Hawaiian guitar",
  verse: "Song section before the chorus",
  violin: "Fiddle",
  vocal: "Of the voice",
  xylophone: "Wooden bars struck with mallets",

  // ---- kitchen
  apron: "Worn over clothes while cooking",
  bake: "Cook in the oven",
  blender: "Machine for smoothies",
  boil: "Heat water until it bubbles",
  bowl: "Round dish for soup or mixing",
  broil: "Cook under direct heat, American style",
  burner: "Ring on the hob",
  casserole: "Slow-cooked dish in a lidded pot",
  chop: "Cut into pieces",
  colander: "Bowl with holes for draining pasta",
  cutlery: "Knives, forks and spoons",
  dice: "Cubes thrown in a game, or cut food into small ones",
  dish: "Plate, or a prepared food",
  fork: "Pronged eating tool",
  freezer: "Coldest part of the fridge",
  fry: "Cook in hot oil",
  grater: "Tool for shredding cheese",
  griddle: "Flat pan for pancakes",
  grill: "Cook over bars and flame",
  kettle: "Boils water for tea",
  knife: "Blade for chopping",
  ladle: "Deep spoon for serving soup",
  mixer: "Stand machine for beating batter",
  napkin: "Cloth or paper for the lap",
  oven: "Hot box for baking",
  pan: "Shallow cooking vessel with a handle",
  pantry: "Cupboard for dry goods",
  peeler: "Tool that strips skin from vegetables",
  plate: "Flat dish you eat from",
  pot: "Deep vessel for stews",
  recipe: "Instructions for a dish",
  roast: "Cook a joint in the oven, or how dark the coffee beans are",
  saucepan: "Deep pan with a long handle",
  sieve: "Mesh for sifting flour",
  simmer: "Cook just below boiling",
  skillet: "Frying pan",
  spatula: "Flat tool for flipping",
  spoon: "Rounded eating tool",
  steam: "Cook over boiling water",
  stove: "Cooker",
  strainer: "Sieve for draining",
  teapot: "Vessel for brewing leaves",
  timer: "It rings when the cake is done",
  toaster: "Browns bread slices",
  tongs: "Tool that grips food with two arms",
  whisk: "Wire tool for beating eggs",

  // ---- halloween
  autumn: "Season of falling leaves",
  bats: "Winged night flyers in the belfry",
  bonfire: "Big outdoor blaze",
  broomstick: "Witch's transport",
  cackle: "Witch's laugh",
  candles: "Wax lights in the window",
  candy: "Sweets, in America",
  cauldron: "Witch's cooking pot",
  cemetery: "Graveyard",
  cobweb: "Dusty spider's net in the corner",
  costume: "Outfit worn to dress up",
  creepy: "Unsettling, giving the shivers",
  crypt: "Underground burial chamber",
  dracula: "Famous count with fangs",
  eerie: "Strangely frightening",
  fangs: "Vampire's sharp teeth",
  frankenstein: "Doctor who built a monster",
  ghost: "Spirit that says boo",
  ghoul: "Grave-robbing spirit",
  goblin: "Mischievous ugly sprite",
  gravestone: "Marker at the head of a plot",
  haunted: "Visited by spirits",
  howl: "Wolf's long cry",
  jackolantern: "Carved, lit pumpkin",
  lantern: "Portable light in a case",
  mask: "Covers the face in disguise",
  midnight: "The witching hour",
  monster: "Frightening creature",
  moonlight: "Glow on a clear night",
  mummy: "Wrapped figure from an Egyptian tomb",
  nightmare: "Bad dream",
  october: "Month that ends with the spooky night",
  ogre: "Man-eating giant of fairy tales",
  owls: "Night birds that hoot",
  phantom: "Ghostly apparition",
  potion: "Magic drink brewed by a witch",
  raven: "Black bird that said nevermore",
  scarecrow: "Straw figure in a field",
  scary: "Frightening",
  shadow: "Dark shape cast by light",
  shriek: "Piercing scream",
  skeleton: "Frame of bones",
  skull: "Bony head",
  spider: "Eight-legged web spinner",
  spooky: "Ghostly and strange",
  tombstone: "Slab over a grave",
  treats: "Sweets, as opposed to tricks",
  vampire: "Blood-drinking creature of the night",
  werewolf: "Man who changes under a full moon",
  witch: "Pointed-hat spell caster",
  wizard: "Male magic worker",
  zombie: "The walking dead",

  // ---- thanksgiving
  abundance: "Plenty",
  blessing: "Grace said before the meal",
  bounty: "Generous harvest",
  bread: "Baked loaf",
  celebrate: "Mark a happy occasion",
  cider: "Drink pressed from apples",
  cornbread: "Golden Southern bake made from maize meal",
  cornucopia: "Horn of plenty",
  cousins: "Your aunt's children",
  cranberry: "Tart red fruit served as a sauce with the turkey",
  dessert: "Sweet final course",
  dinner: "Main meal of the day",
  feast: "Lavish meal",
  gathering: "People coming together",
  grateful: "Thankful",
  gravy: "Sauce made from the roasting juices",
  holiday: "Day off for a celebration",
  hospitality: "Welcoming of guests",
  leftovers: "Food kept for the next day",
  maize: "Corn on the cob, as a crop",
  mashed: "Potatoes beaten smooth",
  napkins: "Set beside every plate",
  november: "Month of the fourth-Thursday holiday",
  nutmeg: "Spice grated over pumpkin pie",
  pecan: "Nut in a Southern pie",
  platter: "Large serving dish",
  potatoes: "Roots mashed or roasted for the table",
  recipes: "Written instructions for dishes",
  relatives: "Family members",
  roasting: "Cooking the bird in the oven",
  settlers: "The first colonists",
  sharing: "Giving others a portion",
  squash: "Gourd vegetable baked in autumn",
  stuffing: "Bread mixture cooked inside the bird",
  sweater: "Knitted top for a cold day",
  thankful: "Full of gratitude",
  yams: "Orange roots baked with marshmallows",

  // ---- easter
  april: "Month the holiday often falls in",
  basket: "Woven container for eggs",
  bonnet: "Decorated hat for the parade",
  bunny: "Rabbit that delivers eggs",
  chicks: "Fluffy yellow hatchlings",
  church: "Place of Sunday worship",
  colors: "Pastels dyed onto eggs",
  decorate: "Adorn with ribbons and paint",
  dyeing: "Colouring the eggs",
  flowers: "Blooms in a spring bouquet",
  grass: "Green shreds lining the basket",
  hidden: "Concealed, like eggs in the garden",
  hunting: "Searching the garden for eggs",
  jellybean: "Small chewy sweet in many colours",
  lamb: "Young sheep, symbol of spring",
  lilies: "White trumpet flowers of the season",
  marshmallow: "Soft sweet shaped like a chick",
  morning: "Time of the sunrise service",
  pastel: "Soft pale colour",
  renewal: "Making new again",
  ritual: "Ceremony repeated each year",
  spring: "Season of new growth",
  sunday: "Day of the holiday",
  sunrise: "Dawn",
  sweets: "Candy",
  vinegar: "Added to the egg dye",
  baskets: "Woven containers for the hunt",
  bouquet: "Bunch of flowers",
  celebration: "Festive occasion",
  springtime: "The season of blossom",

  // ---- valentines
  admire: "Look up to",
  adore: "Love deeply",
  affection: "Fond feeling",
  arrow: "What Cupid fires",
  beloved: "Cherished person",
  cards: "Deck for games, or greetings sent on the 14th",
  charming: "Delightfully attractive",
  cherish: "Hold dear",
  couple: "Two people together",
  crush: "Secret infatuation",
  cupid: "Winged archer of love",
  darling: "Term of endearment",
  date: "Romantic evening out",
  dear: "Beloved; how a letter begins",
  devotion: "Loyal love",
  february: "Month of the 14th",
  fondness: "Warm liking",
  forever: "For all time",
  friendship: "Bond between companions",
  heart: "Symbol of love",
  hugs: "Squeezes with the arms",
  kisses: "Pecks on the lips",
  lace: "Delicate patterned fabric",
  letters: "Written messages of love",
  lovely: "Beautiful",
  loving: "Full of tenderness",
  partner: "Other half",
  passion: "Intense emotion",
  poem: "Verse written for a sweetheart",
  promise: "Pledge",
  red: "Colour of roses and hearts",
  romance: "Love affair",
  romantic: "Given to candlelit dinners",
  roses: "Red flowers by the dozen",
  secret: "Admirer who stays unnamed",
  sweetheart: "Darling",
  together: "In each other's company",
  truffles: "Rich chocolates in a box",
  valentine: "Card, or the person it is sent to",

  // ---- birthday
  balloons: "Inflated party decorations",
  banner: "Sign strung across the room",
  birthday: "Annual celebration of the day you were born",
  blowout: "Extinguishing the candles in one breath",
  bunting: "Strings of little flags",
  cake: "Iced centrepiece with candles",
  cheers: "Toast before drinking",
  confetti: "Paper bits thrown in the air",
  decorations: "Streamers and balloons",
  favors: "Small gifts for the guests",
  frosting: "Sweet coating on a cake",
  friends: "The people you invite",
  games: "Musical chairs and the like",
  gifts: "Wrapped presents",
  goodies: "Treats in the party bag",
  guests: "Those who attend",
  hats: "Paper cones worn at a party",
  icing: "Sugar coating on a cake",
  invitation: "Card asking you to come",
  laughter: "Sound of a good party",
  milestone: "A big round-number year",
  music: "Played for dancing",
  party: "Celebration with guests",
  photos: "Pictures taken to remember the day",
  pinata: "Hanging figure beaten for sweets",
  plates: "Paper dishes for cake",
  singing: "What everyone does before the candles",
  sprinkles: "Coloured sugar bits on top",
  streamers: "Long paper ribbons hung about",
  surprise: "Party the guest of honour did not expect",
  toast: "Raising a glass",
  wishes: "Made before blowing out candles",
  wrapping: "Paper around a gift",
  yearly: "Once every twelve months",
  candlelight: "Glow from the top of the cake",
  memories: "What the photos preserve",

  // ---- wedding
  aisle: "Walked down by the bride",
  anniversary: "Yearly return of the date",
  banquet: "Grand celebratory meal",
  bride: "Woman being married",
  bridesmaid: "Her attendant",
  caterer: "Provides the food",
  ceremony: "The formal exchange of vows",
  champagne: "Sparkling wine for the toast",
  chapel: "Small church",
  dancing: "First one is for the couple",
  dress: "White gown",
  engagement: "Period between proposal and marriage",
  garter: "Band tossed to the single men",
  groom: "Man being married",
  honeymoon: "Holiday after the wedding",
  jewelry: "Rings and necklaces",
  kiss: "Sealed with this at the altar",
  marriage: "The union itself",
  married: "Joined as husband and wife",
  photographer: "Takes the pictures",
  proposal: "Popping the question",
  reception: "Party after the ceremony",
  registry: "List of gifts the couple would like",
  rehearsal: "Practice run the night before",
  rings: "Bands exchanged at the altar",
  speeches: "Best man's moment",
  tuxedo: "Groom's formal suit",
  usher: "Shows guests to their seats",
  veil: "Sheer cloth over the bride's face",
  vows: "Promises made at the altar",
  wedding: "The big day",
  witness: "Signs the register",

  // ---- states
  alabama: "Heart of Dixie, Montgomery's state",
  alaska: "Largest and coldest state",
  arizona: "Grand Canyon state",
  arkansas: "Little Rock's state",
  california: "Golden State",
  colorado: "Rocky Mountain state, Denver",
  delaware: "First state",
  florida: "Sunshine State",
  georgia: "Peach State",
  hawaii: "Island state",
  idaho: "Potato state",
  illinois: "Chicago's state",
  indiana: "Hoosier State",
  iowa: "Corn state with Des Moines",
  kansas: "Sunflower State, Dorothy's home",
  kentucky: "Bluegrass State",
  louisiana: "New Orleans' state",
  maine: "Pine Tree State, far north-east",
  maryland: "State around Chesapeake Bay",
  michigan: "Great Lakes state shaped like a mitten",
  minnesota: "Land of 10,000 lakes",
  mississippi: "Magnolia State on the great river",
  missouri: "Show-Me State",
  montana: "Big Sky Country",
  nebraska: "Cornhusker State",
  nevada: "Silver State with Las Vegas",
  ohio: "Buckeye State",
  oklahoma: "Sooner State",
  oregon: "Beaver State on the Pacific",
  tennessee: "Volunteer State, home of Nashville",
  texas: "Lone Star State",
  utah: "Beehive State",
  vermont: "Green Mountain State",
  virginia: "Old Dominion",
  washington: "Evergreen State, Seattle's home",
  wisconsin: "Badger State, famous for cheese",
  wyoming: "Least populous state, Yellowstone",

  // ---- farm
  acres: "Units of farmland",
  barn: "Big shed for hay and animals",
  barley: "Grain for beer and soup",
  bales: "Bound bundles of hay",
  bucket: "Pail",
  bull: "Male of the herd",
  calf: "Young cow",
  cattle: "Cows and bulls together",
  combine: "Machine that reaps and threshes",
  cornfield: "Where the maize grows",
  cowbell: "Clanker round a grazer's neck",
  crops: "Plants grown for harvest",
  dairy: "Milk-producing farm",
  duckling: "Young waterfowl",
  farmer: "One who works the land",
  feed: "Food given to animals",
  fences: "Boundaries between fields",
  furrow: "Groove cut by a plough",
  goose: "Honking bird, larger than a duck",
  kitchen: "Room where the feast is cooked",
  granary: "Store for grain",
  harness: "Straps for a working horse",
  hayloft: "Upper floor of the barn",
  henhouse: "Where the chickens roost",
  hoof: "Horse's foot",
  horses: "Stabled animals ridden or worked",
  irrigation: "Watering the fields",
  lambs: "Spring's young sheep",
  livestock: "Farm animals",
  manure: "Dung used as fertiliser",
  milking: "Drawing from the cow",
  orchard: "Field of fruit trees",
  pasture: "Grazing land",
  piglet: "Young pig",
  plough: "Tool that turns the soil",
  poultry: "Chickens, ducks and geese",
  rooster: "Cockerel that crows at dawn",
  saddle: "Seat on a horse",
  seeds: "What is sown",
  silo: "Tall tower for grain or silage",
  soil: "Earth in which crops grow",
  stable: "Building for horses",
  tractor: "Farm vehicle that pulls",
  trough: "Long container animals eat from",
  windmill: "Sails that turn to pump or grind",

  // ---- dinosaurs
  allosaurus: "Large Jurassic meat-eater with a three-fingered hand",
  amber: "Fossilised resin that traps insects",
  ancient: "Very old",
  ankylosaurus: "Armoured dinosaur with a club tail",
  archaeology: "Study of the past through digging",
  armor: "Bony plates for protection",
  bones: "What a skeleton is made of",
  brachiosaurus: "Long-necked giant with front legs longer than its back",
  carnivore: "Meat-eater",
  claws: "Curved nails for gripping",
  cretaceous: "Last period of the dinosaurs",
  crest: "Ridge on top of the head",
  dinosaur: "Terrible lizard",
  diplodocus: "Whip-tailed long-necked giant",
  dig: "Excavation site",
  eggs: "Dinosaurs hatched from these",
  extinct: "No longer living",
  ferns: "Fronded plants dinosaurs ate",
  fossil: "Remains preserved in rock",
  gigantic: "Enormous",
  herbivore: "Plant-eater",
  horns: "Pointed growths on the head",
  iguanodon: "Early-named dinosaur with a thumb spike",
  jaws: "Bones that hold the teeth",
  jurassic: "Middle period of the dinosaurs",
  omnivore: "Eats plants and meat",
  paleontology: "Science of fossils",
  predator: "Hunter of other animals",
  prehistoric: "Before written history",
  pterodactyl: "Flying reptile with leathery wings",
  raptor: "Sickle-clawed hunter, for short",
  reptile: "Cold-blooded scaly animal",
  roar: "Loud bellow",
  sauropod: "Long-necked plant-eating giant",
  scales: "Covering of a reptile's skin",
  spikes: "Sharp points along a tail",
  stegosaurus: "Dinosaur with plates down its back",
  swamp: "Marshy wetland",
  tail: "It trails behind",
  teeth: "Used for biting",
  triassic: "First period of the dinosaurs",
  triceratops: "Three-horned dinosaur with a frill",
  tyrannosaurus: "Tyrant king with tiny arms",
  velociraptor: "Fast, feathered pack hunter",

  // ---- camping
  batteries: "Power for the torch",
  bearspray: "Deterrent carried on wild trails",
  binoculars: "Two-eyed viewer for distant things",
  blanket: "Warm covering",
  boots: "Sturdy footwear for the trail",
  campfire: "Where the stories are told",
  campsite: "Pitch for a tent",
  canoe: "Open paddled boat",
  canteen: "Water flask",
  cooler: "Insulated box for food",
  firewood: "Logs for burning",
  firepit: "Ring of stones for burning logs outdoors",
  flashlight: "Torch",
  hammock: "Bed slung between trees",
  hiking: "Long walk in the country",
  insects: "Bugs at the campsite",
  kindling: "Small sticks to start a fire",
  logs: "Cut lengths of tree trunk",
  map: "Paper guide to the terrain",
  matches: "Struck to make a flame",
  mosquito: "Whining biter at dusk",
  outdoors: "The open air",
  pinecone: "Woody seed case that pops in a fire",
  poncho: "Waterproof cape",
  ranger: "Park warden",
  repellent: "Spray that keeps bugs off",
  rope: "Thick cord",
  rucksack: "Bag carried on the back",
  sleeping: "Kind of bag zipped up at night",
  smores: "Toasted marshmallow and chocolate in crackers",
  stargazing: "Looking up on a clear night",
  tent: "Canvas shelter",
  thermos: "Flask that keeps drinks hot",
  wilderness: "Untamed land",
  wildlife: "Untamed creatures",

  // ---- fishing
  angler: "Person with a rod",
  bait: "What is put on the hook",
  boat: "Craft for the water",
  bobber: "Float that dips when a fish bites",
  cast: "Throw the line out",
  catch: "What you bring home",
  creek: "Small stream",
  dock: "Platform where boats tie up",
  fillet: "Boned piece of fish",
  float: "Cork that sits on the surface",
  fly: "Feathered lure for trout",
  freshwater: "Of lakes and rivers, not the sea",
  hook: "Barbed curve on the line",
  jetty: "Landing stage into the water",
  lake: "Large inland body of water",
  license: "Permit to fish",
  line: "Thread from rod to hook",
  lure: "Artificial bait",
  minnow: "Tiny fish, often bait",
  net: "Mesh for landing the catch",
  nibble: "Small bite on the bait",
  perch: "Striped freshwater fish",
  pier: "Long structure out over the water",
  pond: "Small still water",
  reel: "Spool the line winds onto",
  release: "Let the catch go",
  ripple: "Small wave on the surface",
  rod: "Long flexible pole",
  saltwater: "Of the sea",
  sinker: "Weight that takes the bait down",
  sonar: "Sound device that finds fish",
  stream: "Small flowing water",
  tackle: "Fishing gear",
  trout: "Speckled river fish",
  waders: "Waterproof trousers with boots",
  walleye: "Glassy-eyed lake fish",
  worms: "Wrigglers on the hook",

  // ---- cars
  accelerate: "Speed up",
  airbag: "Cushion that inflates in a crash",
  alternator: "Charges the battery while driving",
  axle: "Rod the wheels turn on",
  battery: "Stores the electrical charge",
  brakes: "They slow you down",
  bumper: "Bar at the front and rear",
  carburetor: "Mixes fuel with air in old engines",
  chassis: "Frame of the vehicle",
  clutch: "Pedal pressed to change gear",
  convertible: "Car with a folding roof",
  coolant: "Liquid that stops overheating",
  dashboard: "Panel of dials facing the driver",
  detour: "Route around a closed road",
  diesel: "Heavier fuel for trucks",
  engine: "What is under the hood",
  exhaust: "Pipe for waste gases",
  fender: "Panel over the wheel, American style",
  freeway: "Fast multi-lane road",
  garage: "Where the car sleeps",
  gasoline: "Petrol",
  gearbox: "Transmission housing",
  headlight: "Front lamp",
  hubcap: "Cover on the wheel centre",
  ignition: "Where the key turns",
  junction: "Where roads meet",
  lanes: "Marked strips of a road",
  mileage: "Distance a car has travelled",
  mirror: "Glass for the view behind",
  motor: "Engine",
  muffler: "Silencer on the exhaust",
  odometer: "Dial that counts the miles",
  parking: "Leaving the car in a space",
  pistons: "They pump inside the cylinders",
  radiator: "Cools the engine",
  roadster: "Two-seat open sports car",
  seatbelt: "Strap that holds you in",
  sedan: "Family car with a separate boot, saloon",
  signal: "Blinking indicator",
  spoiler: "Wing on the back of a sports car",
  steering: "Wheel that turns the car",
  suspension: "Springs that smooth the ride",
  throttle: "Accelerator",
  tires: "Rubber round the wheels",
  traffic: "Cars on the road, especially too many",
  transmission: "Gears between engine and wheels",
  trunk: "Boot, in America",
  wipers: "Blades that clear the windscreen",

  // ---- weather
  barometer: "Instrument that measures air pressure",
  chill: "Cold in the air",
  climate: "Typical weather of a region",
  cloudburst: "Sudden heavy downpour",
  cloudy: "Sky covered in grey",
  cyclone: "Spinning tropical storm",
  downpour: "Heavy rain",
  drizzle: "Fine light rain",
  drought: "Long spell without rain",
  flood: "Water where it should not be",
  fog: "Thick low cloud at ground level",
  forecast: "Prediction of tomorrow's weather",
  freezing: "At or below zero",
  gale: "Very strong wind",
  gust: "Sudden burst of wind",
  hail: "Ice pellets falling from a storm",
  haze: "Thin mist that dims the view",
  humid: "Damp and sticky",
  hurricane: "Great Atlantic storm with a name",
  isobar: "Line of equal pressure on a chart",
  lightning: "Flash before the thunder",
  meteorologist: "Weather scientist",
  mist: "Light fog",
  monsoon: "Season of heavy rains in Asia",
  overcast: "Sky fully covered in cloud",
  puddle: "Small pool after rain",
  rainbow: "Arc of colours after a shower",
  rainfall: "Precipitation, as measured in inches",
  sleet: "Rain mixed with snow",
  slush: "Melting snow underfoot",
  snowdrift: "Bank piled up by a blizzard wind",
  snowfall: "Winter precipitation, as measured in inches",
  squall: "Sudden violent gust with rain",
  sunny: "Bright and clear",
  sunshine: "Direct light from the sun",
  temperature: "How hot or cold it is",
  thermometer: "Instrument that measures heat",
  thunder: "Rumble after the flash",
  tornado: "Twisting funnel of wind",
  typhoon: "Pacific hurricane",
  umbrella: "Carried against the rain",
  visibility: "How far you can see",
  wind: "Moving air",

  // ---- jobs
  accountant: "Keeps the books",
  architect: "Designs buildings",
  attorney: "Lawyer",
  baker: "Makes bread and cakes",
  banker: "Works with money and loans",
  barber: "Cuts men's hair",
  biologist: "Studies living things",
  builder: "Constructs houses",
  butcher: "Sells meat",
  captain: "Commands a ship",
  carpenter: "Works with wood",
  cashier: "Takes payment at the till",
  chemist: "Works with substances and reactions",
  curator: "Looks after a museum's collection",
  dentist: "Checks your teeth",
  designer: "Plans how things look",
  detective: "Solves crimes",
  dietitian: "Advises on what to eat",
  editor: "Prepares text for publication",
  electrician: "Wires buildings",
  engineer: "Designs machines and structures",
  firefighter: "Puts out blazes",
  florist: "Sells flowers",
  geologist: "Studies rocks",
  historian: "Studies the past",
  instructor: "One who teaches a skill",
  janitor: "Keeps a building clean",
  jeweler: "Sells rings and watches",
  journalist: "Reports the news",
  judge: "Presides over a court",
  librarian: "Keeps the books in order",
  locksmith: "Tradesman who cuts keys",
  machinist: "Operates metal-cutting machines",
  mechanic: "Fixes cars",
  midwife: "Helps deliver babies",
  musician: "Plays an instrument for a living",
  nurse: "Cares for patients",
  optician: "Fits glasses",
  painter: "Works with brushes and colour",
  paramedic: "Emergency responder in the ambulance",
  pharmacist: "Dispenses medicines",
  pilot: "Flies the plane",
  plumber: "Fixes pipes",
  professor: "Senior university teacher",
  surgeon: "Doctor who operates",
  teacher: "Instructs a class",
  therapist: "Helps people through talking",
  translator: "Turns one language into another",
  veterinarian: "Animal doctor",
  welder: "Joins metal with heat",

  // ---- school
  algebra: "Maths with letters",
  alphabet: "The 26 letters in order",
  assembly: "Whole-school gathering",
  assignment: "Set piece of work",
  biology: "Science of living things",
  cafeteria: "School dining hall",
  calculator: "Device for sums",
  chalkboard: "Blackboard",
  chemistry: "Science of substances",
  classroom: "Where pupils sit for lessons",
  crayons: "Waxy colouring sticks",
  detention: "Kept in after school",
  diploma: "Certificate at graduation",
  eraser: "Rubs out pencil marks",
  exam: "Formal test",
  folder: "Holds loose papers",
  geography: "Study of the earth and its countries",
  geometry: "Maths of shapes and angles",
  glue: "Sticky paste for craft",
  grades: "Marks awarded for work",
  gymnasium: "Hall for PE",
  highlighter: "Bright marker pen",
  history: "Study of the past",
  homework: "Assignment done after school",
  laboratory: "Room for science experiments",
  lessons: "Periods of teaching",
  library: "Room of borrowed books",
  lockers: "Metal cupboards in the corridor",
  lunchbox: "Container for a packed meal",
  notebook: "Bound pages for jottings",
  notes: "Jottings taken in class",
  principal: "Head of the school",
  project: "Extended piece of work",
  quiz: "Short test",
  recess: "Break between lessons",
  report: "End-of-term account of progress",
  ruler: "Straight edge marked in inches",
  scissors: "Two blades for cutting",
  semester: "Half of the school year",
  spelling: "Test of how words are written",
  stapler: "Fastens pages together",
  students: "Those who learn",
  studying: "Revising for a test",
  textbook: "Set volume for a subject",
  uniform: "Clothes all pupils wear",
  yearbook: "Annual with everyone's photo",

  // ---- baby
  babble: "Baby's first sounds",
  bassinet: "Small basket bed",
  bib: "Cloth to catch the spills",
  booties: "Tiny knitted shoes",
  bottle: "Holds the milk",
  bouncer: "Springy seat for a baby",
  burp: "Wind brought up after feeding",
  carriage: "Pram",
  cradle: "Rocking bed",
  crawling: "Getting about on hands and knees",
  crib: "Baby's barred cot",
  cuddle: "Warm hug",
  diaper: "Nappy, in America",
  dummy: "Pacifier, in Britain",
  formula: "Powdered milk for a bottle",
  giggle: "Small laugh",
  grandparents: "Nana and grandad",
  highchair: "Tall seat for meals",
  hospital: "Where most babies are born",
  infant: "Very young child",
  lullaby: "Song to send a baby to sleep",
  mittens: "Coverings for small hands",
  mobile: "Dangling toy over the cot",
  monitor: "Device that listens in the nursery",
  nappy: "Diaper, in Britain",
  newborn: "Just arrived",
  nursery: "Baby's room",
  onesie: "One-piece baby suit",
  pacifier: "Dummy, in America",
  playpen: "Fenced enclosure for a toddler",
  rattle: "Toy that shakes noisily",
  rocking: "Kind of chair for soothing",
  romper: "One-piece play outfit",
  shower: "Party for the mother-to-be",
  sleeper: "Footed pyjama suit",
  sleepy: "Ready for a nap",
  snuggle: "Nestle close",
  stroller: "Pushchair",
  swaddle: "Wrap snugly in a blanket",
  teething: "Painful stage when the first molars come through",
  toddler: "Child just learning to walk",
  toys: "Things to play with",
  wipes: "Moist cloths for cleaning up",
  yawn: "Wide-mouthed sign of tiredness",

  // ---- coffee & tea
  americano: "Espresso lengthened with hot water",
  aroma: "Pleasant smell",
  barista: "Person who makes the coffee",
  beans: "Roasted and ground for the cup",
  bergamot: "Citrus that flavours a famous tea",
  blend: "Mix of different beans or leaves",
  brewing: "Steeping or percolating",
  cafe: "Coffee shop",
  caffeine: "The stimulant in the cup",
  cappuccino: "Espresso with foamed milk",
  chamomile: "Calming flower tea",
  cortado: "Espresso cut with equal milk",
  cream: "Thick top of the milk",
  cupping: "Tasting coffee professionally",
  darjeeling: "Champagne of teas, from the Himalayas",
  decaf: "Without the stimulant",
  earlgrey: "Black tea scented with bergamot",
  espresso: "Small strong shot",
  filter: "Paper the coffee drips through",
  flatwhite: "Espresso with velvety milk, Antipodean style",
  foam: "Frothed milk on top",
  grinder: "Turns beans to powder",
  herbal: "Tea made from leaves other than tea",
  infusion: "Drink made by steeping",
  latte: "Milky espresso drink",
  macchiato: "Espresso marked with a dab of foam",
  matcha: "Powdered green tea",
  milk: "White splash added to the cup",
  mocha: "Coffee with chocolate",
  mug: "Big handled cup",
  oolong: "Tea between green and black",
  percolator: "Pot that bubbles coffee up through a tube",
  plunger: "Press in a cafetière",
  pourover: "Coffee made by hand through a cone",
  rooibos: "Red bush tea from South Africa",
  saucer: "Small plate under a cup",
  scone: "Bake served with jam and cream",
  steeping: "Leaving leaves in hot water",
  sugar: "Sweetener by the spoon",
  teabag: "Leaves in a little pouch",
  teaspoon: "Small stirrer",

  // ---- birds
  albatross: "Ocean wanderer with the widest wings",
  aviary: "Large cage for birds",
  beak: "Bird's bill",
  bluebird: "Sky-coloured songbird of happiness",
  cardinal: "Bright red crested songbird",
  chickadee: "Small bird named for its call",
  condor: "Huge vulture of the Andes",
  cormorant: "Diving sea bird that dries its wings",
  crane: "Tall, long-legged wader that dances",
  crow: "Black bird that caws",
  cuckoo: "Bird that lays in others' nests",
  dove: "Bird of peace",
  eagle: "Great bird of prey, national emblem",
  egret: "White heron",
  falcon: "Fast hunting bird flown from the fist",
  feathers: "A bird's covering",
  finch: "Small seed-eating songbird",
  goldfinch: "Yellow-winged seed-eater with a red face",
  grouse: "Moorland game bird, or to complain",
  fledgling: "Young bird just able to fly",
  gull: "Sea bird that steals chips",
  hawk: "Sharp-eyed hunter of the sky",
  heron: "Long-legged fisher that stands still",
  hummingbird: "Tiny hoverer that drinks nectar",
  jay: "Noisy, colourful crow relative",
  kestrel: "Small falcon that hovers over roads",
  kingfisher: "Brilliant blue diver of riverbanks",
  lark: "Songbird that rises singing at dawn",
  magpie: "Black-and-white bird said to steal shiny things",
  migration: "Seasonal journey of flocks",
  mockingbird: "Songster that copies others' tunes",
  nest: "Home built for eggs",
  nightingale: "Famed singer after dark",
  oriole: "Orange-and-black songbird",
  osprey: "Fish-eating hawk",
  owl: "Wise night bird",
  plumage: "A bird's feathers as a whole",
  quail: "Small plump game bird",
  roost: "Where birds settle at night",
  sparrow: "Common little brown bird",
  starling: "Glossy bird that flocks in murmurations",
  stork: "Long-legged bird said to bring babies",
  swallow: "Fork-tailed summer visitor",
  swan: "Graceful white bird with a long neck",
  talons: "Claws of a bird of prey",
  thrush: "Speckled-breasted songbird",
  vulture: "Bald scavenger that circles",
  warbler: "Small bird with a trilling song",
  woodpecker: "Bird that drums on trunks",
  wren: "Tiny brown bird with a cocked tail",

  // ---- flowers
  amaryllis: "Big red trumpet grown indoors at Christmas",
  aster: "Star-shaped autumn daisy",
  begonia: "Waxy-leaved bedding plant",
  buttercup: "Glossy yellow meadow flower",
  camellia: "Glossy shrub with rose-like winter blooms",
  carnation: "Frilled buttonhole flower",
  chrysanthemum: "Mum, the autumn bloom",
  clematis: "Climber with large starry flowers",
  cornflower: "Bright blue bloom of the wheat field",
  crocus: "First bulb to push through the snow",
  delphinium: "Tall spike of blue summer flowers",
  forgetmenot: "Small blue flower with a plea in its name",
  freesia: "Highly scented flower on an arching stem",
  gardenia: "Creamy white bloom with a heavy scent",
  gladiolus: "Sword-leaved spike of flowers",
  hydrangea: "Shrub with big mophead blooms",
  lotus: "Sacred water flower of the East",
  sweetpea: "Scented climber with ruffled petals",

  // ---- desserts
  banoffee: "Pie of bananas and toffee",
  biscotti: "Twice-baked Italian biscuits",
  brownie: "Dense chocolate square",
  butterscotch: "Brown-sugar confection, or its sauce on ice cream",
  cannoli: "Crisp tubes filled with ricotta",
  caramel: "Sugar cooked until golden",
  cheesecake: "Rich dessert on a biscuit base",
  churros: "Fried dough sticks dusted with sugar",
  cobbler: "Fruit baked under a scone topping",
  compote: "Fruit stewed in syrup",
  crumble: "Fruit under a buttery topping",
  custard: "Sweet yellow sauce of eggs and milk",
  doughnut: "Fried ring, British spelling",
  eclair: "Choux finger filled with cream",
  flan: "Set custard with caramel",
  fritter: "Fruit fried in batter",
  fudge: "Soft crumbly sweet",
  ganache: "Chocolate and cream glaze",
  gelato: "Italian ice cream",
  macaron: "Delicate French almond sandwich biscuit",
  marzipan: "Almond paste for icing cakes",
  meringue: "Whipped egg white baked crisp",
  mousse: "Airy chocolate dessert",
  nougat: "Chewy sweet with nuts",
  pastry: "Dough for pies and tarts",
  pavlova: "Meringue base piled with cream and fruit",
  praline: "Nuts set in caramelised sugar",
  pudding: "Dessert, in Britain",
  sherbet: "Fruity frozen dessert, or fizzy powder",
  shortcake: "Strawberries and cream on a crumbly base",
  sorbet: "Dairy-free frozen fruit dessert",
  souffle: "Dessert that rises and must be served at once",
  strudel: "Rolled pastry with apple",
  sundae: "Ice cream with sauce and toppings",
  syrup: "Thick sweet liquid",
  tartlet: "Small open pastry",
  tiramisu: "Coffee-soaked Italian dessert",
  toffee: "Hard chewy sweet of boiled sugar",
  trifle: "Layers of sponge, fruit, custard and cream",
  truffle: "Rich chocolate ball",
  waffles: "Grid-patterned cakes, served stacked",
  whipped: "Cream beaten until it holds",

  // ---- games night
  backgammon: "Race game with checkers and dice",
  bidding: "Offering a price, in bridge or an auction",
  bishop: "Chess piece that moves diagonally",
  bluffing: "Pretending to hold a better hand",
  board: "What the pieces move on",
  bonus: "Extra points",
  charades: "Acting out a title without words",
  checkers: "Draughts, in America",
  chess: "Game of kings and queens",
  counters: "Tokens moved around the board",
  cribbage: "Card game scored on a pegboard",
  dealer: "One who hands out the cards",
  dominoes: "Tiles with spots, laid end to end",
  draughts: "Checkers, in Britain",
  expansion: "Add-on set for a game",
  gambit: "Opening sacrifice in chess",
  hearts: "Card game where you avoid the queen of spades",
  jigsaw: "Picture cut into interlocking pieces",
  joker: "Wild card",
  knight: "Chess piece that jumps in an L",
  mahjong: "Chinese tile game",
  marbles: "Glass balls flicked in a ring",
  meeple: "Little wooden person in modern board games",
  opponent: "The one you play against",
  pawn: "Humblest chess piece",
  penalty: "Points lost for breaking a rule",
  pieces: "The parts you move",
  player: "One taking part",
  points: "The score",
  puzzle: "Problem to be solved for fun",
  reshuffle: "Mix the cards again",
  rook: "Castle piece in chess",
  roll: "Throw of the dice",
  rules: "How the game is played",
  scoring: "Keeping count of points",
  scrabble: "Word game on a lettered board",
  shuffle: "Mix the deck",
  solitaire: "Card game for one",
  spinner: "Arrow spun instead of dice",
  strategy: "Long-term plan to win",
  tiles: "Flat pieces, as in dominoes",
  tokens: "Markers standing for players",
  trivia: "Quiz of general knowledge",
  turns: "Each player's go, in order",
  victory: "Winning",
  wager: "Bet",

  // ---- beach
  bathers: "Swimmers, or their costume",
  boardwalk: "Wooden promenade along the sand",
  bodyboard: "Short foam plank ridden lying down",
  breakers: "Waves crashing on the shore",
  buckets: "Pails for sandcastles",
  cabana: "Small shelter on the sand",
  cove: "Small sheltered bay",
  deckchair: "Folding canvas seat",
  dunes: "Hills of wind-blown sand",
  flippers: "Fins worn for swimming",
  flotsam: "Wreckage floating on the sea",
  goggles: "Eye protection under water",
  harbour: "Sheltered port, British spelling",
  horizon: "Line where sea meets sky",
  icecream: "Cone bought from a van",
  lifeguard: "Watcher who rescues swimmers",
  lilo: "Inflatable mattress for floating",
  lotion: "Cream rubbed on to protect the skin",
  paddling: "Wading in the shallows",
  parasol: "Sun umbrella",
  pebbles: "Small smooth stones",
  picnic: "Meal eaten outdoors from a basket",
  sandals: "Open summer shoes",
  sandcastle: "Turreted creation on the beach",
  seagull: "Coastal bird after your chips",
  shore: "Edge of the land",
  sunburn: "Red skin from too much sun",
  sunhat: "Wide brim against the glare",
  sunscreen: "Lotion with an SPF",
  surfboard: "Long plank for riding waves",
  swimsuit: "Bathing costume",
  tanning: "Browning in the sun",
  towel: "Cloth for drying off",
  waves: "Rollers that break on the shore",
};
